site_name: RobotFramework-Airtest
site_url: https://kaluluosi.github.io/robotframework-airtest
site_description: "A Robot Framework library for Airtest."

repo_url: https://github.com/kaluluosi/robotframework-airtest

theme: 
    name: material
    features:
      - navigation.instant
      - navigation.instant.prefetch
      - navigation.instant.progress
      - navigation.tracking
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.sections
      - navigation.expand
      - navigation.path
      - navigation.indexes
      - toc.follow
      - toc.integrate
      - navigation.top
      - search.suggest
      - search.highlight
      - search.share
      - content.code.copy
      - content.code.select
      - content.code.annotate

plugins:
  - search

nav:
    - 首页: index.md
    - 入门: 
        - quick_start/index.md
        - 安装: quick_start/0_install.md
        - 创建项目: quick_start/1_create_project.md
        - 开发环境配置: quick_start/2_dev_env.md
        - 前端接入: quick_start/3_frontend.md
    - 高级: 
        - advance/index.md
        - 基础篇: advance/basic.md
        - 中级篇: advance/intermediate.md
        - 高级篇: advance/advance.md
    - 自动化集成:
        - ci_cd/index.md
    - 接口文档:
        - libs/index.md
        - DeviceLibrary:  libs/DeviceLibrary.html
        - StdPocoLibrary: libs/StdPocoLibrary.html
        - UnityPocoLibrary: libs/UnityPocoLibrary.html

    - 参考文档: 
        - references.md
        - 中文文档: https://robotframework-userguide-cn.readthedocs.io/zh_CN/latest/
        - 官方文档: https://robotframework.org/robotframework/
        - 内置关键字文档: https://robotframework.org/robotframework/latest/libraries/BuiltIn.html

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - tables
  - codehilite