site_name: RobotFramework-Airtest
site_url: https://kaluluosi.github.io/robotframework-airtest
site_description: "A Robot Framework library for Airtest."

repo_url: https://github.com/kaluluosi/robotframework-airtest

theme: 
    name: material
    features:
      - navigation.instant
      - navigation.instant.prefetch
      - navigation.instant.progress
      - navigation.tracking
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.sections
      - navigation.expand
      - navigation.path
      - navigation.indexes
      - toc.follow
      - toc.integrate
      - navigation.top
      - search.suggest
      - search.highlight
      - search.share

plugins:
  - search

nav:
    - 首页: index.md
    - 入门: 
        - quick_start/index.md
        - 创建项目: quick_start/1_create_project.md
        - 开发环境配置: quick_start/2_dev_env.md
        - 前端接入: quick_start/3_frontend.md
    - 高级: 
        - advance/index.md
    - 自动化集成:
        - ci_cd/index.md
    - 参考文档: references.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - tables