
name: publish-docs
on:
    workflow_call:
        inputs:
            deploy:
                type: boolean
                default: false
                required: true
                description: 
                    Whether to deploy the docs or not.
    workflow_dispatch:
        inputs:
            deploy:
                type: boolean
                default: false
                required: true
                description: 
                    Whether to deploy the docs or not.

permissions:
    contents: write

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v4
          with:
            python-version: '3.8'
        - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
        
        - uses: actions/cache@v3
          with:
            key: mkdocs-material-${{env.cache_id}}
            path: .cache
            restore-keys:
              mkdocs-material-
        - run: pip install mkdocs-material
        - run: mkdocs gh-deploy --force
