
name: publish-docs
on:
    push:
        paths:
            - "docs/**"
    pull_request:
        paths:
            - "docs/**"
            
    workflow_call:
        inputs:
            deploy:
                type: boolean
                default: false
                required: true
                description: 
                    Whether to deploy the docs or not.
    workflow_dispatch:
        inputs:
            deploy:
                type: boolean
                default: false
                required: true
                description: 
                    Whether to deploy the docs or not.

permissions:
    contents: write

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout-检出项目
            uses: actions/checkout@v4

          - name: Env Setup
            uses: ./.github/actions/env_setup
        
          - name: Build-生成文档
            run: |
                poetry run mkdocs build

          - name: Deploy-部署文档
            if: github.event.inputs.deploy == true
            run: |
                poetry run mkdocs gh-deploy --force