# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
        version:
          description: package version
          type: string
          required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
        - name: Env Setup
          uses: ./.github/actions/env_setup
        
        - name: 将Tag版本号填写到toml配置中
          if: github.event.release.tag_name
          run: poetry version ${{github.event.release.tag_name}}

        - name: 将version参数更新到toml配置中
          if: github.event.inputs.version
          run: poetry version ${{github.event.inputs.version}}

        - name: Install dependencies
          run: |
              poetry install
        - name: Build package
          run:  poetry build
        - name: Publish package
          run: |
            poetry publish --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}         

  docs:
    needs: [ deploy ]
    uses: ./.github/workflows/docs.yml
    with:
        deploy: true