name: Test-测试


on:
    push:
        paths-ignore:
            - ".github/**"
        branches-ignore:
            - gh-pages
    pull_request:
        paths-ignore:
            - ".github/**"
    
    workflow_dispatch:
    workflow_call:


jobs:
    test-android:
        runs-on: windows-latest
        steps:
            - name: Checkout-检出项目
              uses: actions/checkout@v4
            
            - name: List File
              run: ls -a

            - name: Env Setup
              uses: ./.github/actions/env_setup

