name: Test-测试


on:
    push:
        paths-ignore:
            - ".github/**"
        branches-ignore:
            - gh-pages
    pull_request:
        paths-ignore:
            - ".github/**"
    
    workflow_dispatch:
    workflow_call:

env:
    PYTHONUTF8: 1

jobs:


    test-android:
        runs-on: windows-latest
        steps:
            - name: Checkout-检出项目
              uses: actions/checkout@v4

            - name: Env Setup
              uses: ./.github/actions/env_setup

